version: '3.8'

services:
  postgresql:
    image: postgres:12
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - test_vol:/var/lib/postgresql/data

volumes:
  test_vol:
    driver: local
